name: Build Using Env Variables and Secrets

on: push

env:
  IMAGE_NAME: ${{ vars.IMAGE_NAME  }}
  DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Docker Login
      run: echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

    - name: Docker Build
      run: docker build -t "$DOCKER_USERNAME/$IMAGE_NAME:latest" .

    - name: Docker Publish
      run: docker push "$DOCKER_USERNAME/$IMAGE_NAME:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Docker Run
        run: echo docker run -d -p 8085:8085 "$DOCKER_USERNAME/$IMAGE_NAME:latest"
